export * from "./HomePage/Home";
export * from "./Login/Login";
export * from "./Register/Register";
export * from "./Terms/Terms";
export * from "./AiTools/AiNutrition";
export * from "./TryNow/TryNow";
export * from "./RequestDemo/Request";
export * from "./AiTools/AiTrainer";
export * from "./Pricing/Pricing";
